import { promises as fs } from "node:fs";
import path from "node:path";
import { rimraf } from "rimraf";
import { type Registry, registrySchema } from "shadcn/schema";

import { registry } from "../registry/index";

const REGISTRY_PATH = path.join(process.cwd(), "__registry__");
const REGISTRY_FILENAME = "registry.autogenerated.json";
const PUBLIC_REGISTRY_PATH = path.join(process.cwd(), "public/r");

const buildRegistry = async (registry: Registry) => {
  let index = `/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import * as React from "react"

export const Index: Record<string, any> = {`;

  for (const item of registry.items) {
    if (!Array.isArray(item.files) || !item.files?.length) {
      continue;
    }

    const componentPath = `@/registry/${item.files[0].path}`;

    index += `
  "${item.name}": {
    name: "${item.name}",
    description: "${item.description ?? ""}",
    type: "${item.type}",
    files: [${item.files.map((file) => {
      const filePath = file.path;
      return `{
      path: "${filePath}",
      type: "${file.type}",
    }`;
    })}],${
      item.type === "registry:example"
        ? `
    component: React.lazy(async () => {
      const mod = await import("${componentPath}")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),`
        : ""
    }
  },`;
  }

  index += `
}`;

  const registryJSON = JSON.stringify(
    {
      $schema: "https://ui.shadcn.com/schema/registry.json",
      name: "zenincharts",
      homepage: "https://charts.zenin.design/",
      items: registry.items
        .filter((item) => item.type !== "registry:example")
        .map((item) => {
          return {
            ...item,
            files: item.files ?? [],
          };
        }),
    },
    null,
    2,
  );
  rimraf.sync(path.join(REGISTRY_PATH, REGISTRY_FILENAME));
  await fs.writeFile(
    path.join(REGISTRY_PATH, REGISTRY_FILENAME),
    registryJSON,
    "utf8",
  );
  // Build /src/__registry__/index.tsx
  rimraf.sync(path.join(REGISTRY_PATH, "index.tsx"));
  await fs.writeFile(path.join(REGISTRY_PATH, "index.tsx"), index, "utf8");
};
try {
  console.log("⏺ Building registry...");

  const result = registrySchema.safeParse(registry);

  if (!result.success) {
    console.error(result.error);
    process.exit(1);
  }

  await buildRegistry(result.data);

  console.log("✅ Done!");
} catch (error) {
  console.error(error);
  process.exit(1);
}
