/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import * as React from "react"

export const Index: Record<string, any> = {
  "crypto-price-chart": {
    name: "crypto-price-chart",
    description: "Interactive animated crypto price chart with tabs and holdings summary.",
    type: "registry:component",
    files: [{
      path: "registry/default/ui/crypto-price-chart.tsx",
      type: "registry:component",
    }],
  },
}