/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import * as React from "react"

export const Index: Record<string, any> = {
  "crypto-price-chart": {
    name: "crypto-price-chart",
    description: "Interactive animated crypto price chart with tabs and holdings summary.",
    type: "registry:component",
    files: [{
      path: "registry/default/ui/crypto-price-chart.tsx",
      type: "registry:component",
    },{
      path: "registry/default/ui/crypto-price-chart-data.ts",
      type: "registry:component",
    }],
  },
  "members-growth-chart": {
    name: "members-growth-chart",
    description: "Sleek analytics chart with tabbed segments and gradient area visualization.",
    type: "registry:component",
    files: [{
      path: "registry/default/ui/members-growth-chart.tsx",
      type: "registry:component",
    },{
      path: "registry/default/ui/members-growth-chart-data.ts",
      type: "registry:component",
    }],
  },
  "momentum-chart": {
    name: "momentum-chart",
    description: "Displays a metric’s value, change, and trend to highlight momentum over time.",
    type: "registry:component",
    files: [{
      path: "registry/default/ui/momentum-chart.tsx",
      type: "registry:component",
    },{
      path: "registry/default/ui/dot-pattern.tsx",
      type: "registry:component",
    }],
  },
}